---
- name: Configure k3s workers
  hosts: k3s_workers
  become: true
  gather_facts: true

  tasks:
    - name: Download k3s installation script
      ansible.builtin.get_url:
        url: https://get.k3s.io
        dest: /tmp/k3s_install.sh
        mode: "0700"

    - name: Check if k3s agent is already installed
      ansible.builtin.stat:
        path: /usr/local/bin/k3s-agent
      register: k3s_agent

    - name: Install k3s agent
      ansible.builtin.shell: |
        K3S_URL="https://{{ hostvars[groups['k3s_master'][0]].master_ip }}:6443" \
        K3S_TOKEN="{{ hostvars[groups['k3s_master'][0]].cluster_token }}" \
        INSTALL_K3S_VERSION="{{ k3s_version }}" \
        INSTALL_K3S_EXEC="agent --node-name {{ inventory_hostname }}" \
        /tmp/k3s_install.sh
      when: not k3s_agent.stat.exists
      changed_when: true

    - name: Ensure k3s-agent service is enabled and running
      ansible.builtin.systemd:
        name: k3s-agent
        enabled: true
        state: started
