apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "novu.fullname" . }}-config
  labels:
    {{- include "novu.labels" . | nindent 4 }}
data:
  NODE_ENV: {{ .Values.appConfig.NODE_ENV | quote }}
  API_ROOT_URL: {{ default (printf "http://%s-api:%v" (include "novu.fullname" .) (.Values.services.api.service.port | int)) .Values.appConfig.API_ROOT_URL | quote }}
  FRONT_BASE_URL: {{ .Values.appConfig.FRONT_BASE_URL | quote }}
  MONGO_MIN_POOL_SIZE: {{ .Values.appConfig.MONGO_MIN_POOL_SIZE | quote }}
  MONGO_MAX_POOL_SIZE: {{ .Values.appConfig.MONGO_MAX_POOL_SIZE | quote }}
  REDIS_HOST: {{ printf "%s-redis-headless" (include "novu.fullname" .) | quote }}
  REDIS_PORT: {{ .Values.redis.service.port | quote }}
  REDIS_DB_INDEX: {{ .Values.appConfig.REDIS_DB_INDEX | quote }}
  REDIS_CACHE_SERVICE_HOST: {{ printf "%s-redis-headless" (include "novu.fullname" .) | quote }}
  REDIS_CACHE_SERVICE_PORT: {{ .Values.redis.service.port | quote }}
  S3_LOCAL_STACK: {{ .Values.appConfig.S3_LOCAL_STACK | quote }}
  S3_BUCKET_NAME: {{ .Values.appConfig.S3_BUCKET_NAME | quote }}
  S3_REGION: {{ .Values.appConfig.S3_REGION | quote }}
  SUBSCRIBER_WIDGET_JWT_EXPIRATION_TIME: {{ .Values.appConfig.SUBSCRIBER_WIDGET_JWT_EXPIRATION_TIME | quote }}
  SENTRY_DSN: {{ .Values.appConfig.SENTRY_DSN | quote }}
  NEW_RELIC_ENABLED: {{ .Values.appConfig.NEW_RELIC_ENABLED | quote }}
  NEW_RELIC_APP_NAME: {{ .Values.appConfig.NEW_RELIC_APP_NAME | quote }}
  API_CONTEXT_PATH: {{ .Values.appConfig.API_CONTEXT_PATH | quote }}
  WS_CONTEXT_PATH: {{ .Values.appConfig.WS_CONTEXT_PATH | quote }}
  MONGO_AUTO_CREATE_INDEXES: {{ .Values.appConfig.MONGO_AUTO_CREATE_INDEXES | quote }}
  IS_API_IDEMPOTENCY_ENABLED: {{ .Values.appConfig.IS_API_IDEMPOTENCY_ENABLED | quote }}
  IS_API_RATE_LIMITING_ENABLED: {{ .Values.appConfig.IS_API_RATE_LIMITING_ENABLED | quote }}
  IS_NEW_MESSAGES_API_RESPONSE_ENABLED: {{ .Values.appConfig.IS_NEW_MESSAGES_API_RESPONSE_ENABLED | quote }}
  IS_V2_ENABLED: {{ .Values.appConfig.IS_V2_ENABLED | quote }}
  IS_SELF_HOSTED: {{ .Values.appConfig.IS_SELF_HOSTED | quote }}
  BROADCAST_QUEUE_CHUNK_SIZE: {{ .Values.appConfig.BROADCAST_QUEUE_CHUNK_SIZE | quote }}
  MULTICAST_QUEUE_CHUNK_SIZE: {{ .Values.appConfig.MULTICAST_QUEUE_CHUNK_SIZE | quote }}
  IS_EMAIL_INLINE_CSS_DISABLED: {{ .Values.appConfig.IS_EMAIL_INLINE_CSS_DISABLED | quote }}
  IS_USE_MERGED_DIGEST_ID_ENABLED: {{ .Values.appConfig.IS_USE_MERGED_DIGEST_ID_ENABLED | quote }}
  VITE_API_HOSTNAME: {{ .Values.appConfig.VITE_API_HOSTNAME | quote }}
  VITE_WEBSOCKET_HOSTNAME: {{ .Values.appConfig.VITE_WEBSOCKET_HOSTNAME | quote }}
