---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "novu.fullname" . }}-redis-headless
  labels:
    {{- include "novu.labels" . | nindent 4 }}
    app.kubernetes.io/component: redis
spec:
  clusterIP: None
  publishNotReadyAddresses: true
  ports:
    - name: redis
      port: {{ .Values.redis.service.port }}
      targetPort: redis
      protocol: TCP
  selector:
    {{- include "novu.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: redis
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "novu.fullname" . }}-mongodb-headless
  labels:
    {{- include "novu.labels" . | nindent 4 }}
    app.kubernetes.io/component: mongodb
spec:
  clusterIP: None
  publishNotReadyAddresses: true
  ports:
    - name: mongodb
      port: {{ .Values.mongodb.service.port }}
      targetPort: mongodb
      protocol: TCP
  selector:
    {{- include "novu.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: mongodb
