apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "novu.fullname" . }}-redis
  labels:
    {{- include "novu.labels" . | nindent 4 }}
    app.kubernetes.io/component: redis
spec:
  serviceName: {{ include "novu.fullname" . }}-redis-headless
  replicas: {{ .Values.redis.replicas }}
  selector:
    matchLabels:
      {{- include "novu.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: redis
  template:
    metadata:
      annotations:
        {{- toYaml .Values.podAnnotations | nindent 8 }}
      labels:
        {{- include "novu.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: redis
    spec:
      securityContext:
        {{- toYaml .Values.redis.securityContext | nindent 8 }}
      initContainers:
        - name: volume-permissions
          image: busybox
          securityContext:
            runAsUser: 0
            runAsGroup: 0
          command:
            - sh
            - -c
            - |
              chown -R 1001:1001 /data
          volumeMounts:
            - name: data
              mountPath: /data
      containers:
        - name: redis
          securityContext:
            {{- toYaml .Values.redis.securityContext | nindent 12 }}
          image: "{{ .Values.redis.image.repository }}:{{ .Values.redis.image.tag }}"
          imagePullPolicy: {{ .Values.redis.image.pullPolicy }}
          {{- if .Values.redis.auth.enabled }}
          args:
            - redis-server
            - --appendonly
            - "yes"
            - --requirepass
            - $(REDIS_PASSWORD)
          env:
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "novu.fullname" . }}-secret
                  key: REDIS_PASSWORD
          {{- else }}
          args:
            - redis-server
            - --appendonly
            - "yes"
          {{- end }}
          ports:
            - name: redis
              containerPort: {{ .Values.redis.service.port }}
              protocol: TCP
          {{- if .Values.redis.auth.enabled }}
          livenessProbe:
            exec:
              command:
                - sh
                - -c
                - redis-cli -a "$REDIS_PASSWORD" ping
            initialDelaySeconds: 20
            periodSeconds: 10
          readinessProbe:
            exec:
              command:
                - sh
                - -c
                - redis-cli -a "$REDIS_PASSWORD" ping
            initialDelaySeconds: 5
            periodSeconds: 10
          {{- else }}
          livenessProbe:
            exec:
              command:
                - redis-cli
                - ping
            initialDelaySeconds: 20
            periodSeconds: 10
          readinessProbe:
            exec:
              command:
                - redis-cli
                - ping
            initialDelaySeconds: 5
            periodSeconds: 10
          {{- end }}
          volumeMounts:
            - name: data
              mountPath: /data
          resources:
            {{- toYaml .Values.redis.resources | nindent 12 }}
      {{- $nodeSelector := default .Values.nodeSelector .Values.redis.nodeSelector }}
      {{- with $nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- $affinity := default .Values.affinity .Values.redis.affinity }}
      {{- with $affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- $tolerations := default .Values.tolerations .Values.redis.tolerations }}
      {{- with $tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
  volumeClaimTemplates:
    - metadata:
        name: data
        labels:
          {{- include "novu.labels" . | nindent 10 }}
          app.kubernetes.io/component: redis
      spec:
        accessModes:
          {{- toYaml .Values.redis.persistence.accessModes | nindent 10 }}
        storageClassName: {{ include "novu.storageClassName" . | quote }}
        resources:
          requests:
            storage: {{ .Values.redis.persistence.size | quote }}
