apiVersion: v1
kind: Secret
metadata:
  name: {{ include "novu.fullname" . }}-secret
  labels:
    {{- include "novu.labels" . | nindent 4 }}
type: Opaque
stringData:
  MONGO_INITDB_ROOT_USERNAME: {{ .Values.secrets.MONGO_INITDB_ROOT_USERNAME | quote }}
  MONGO_INITDB_ROOT_PASSWORD: {{ .Values.secrets.MONGO_INITDB_ROOT_PASSWORD | quote }}
  MONGO_URL: {{ include "novu.mongoUrl" . | quote }}
  REDIS_PASSWORD: {{ .Values.secrets.REDIS_PASSWORD | quote }}
  AWS_ACCESS_KEY_ID: {{ .Values.secrets.AWS_ACCESS_KEY_ID | quote }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.secrets.AWS_SECRET_ACCESS_KEY | quote }}
  JWT_SECRET: {{ include "novu.generatedSecret" (dict "root" . "key" "JWT_SECRET" "value" .Values.secrets.JWT_SECRET "length" 64) | quote }}
  STORE_ENCRYPTION_KEY: {{ include "novu.generatedSecret" (dict "root" . "key" "STORE_ENCRYPTION_KEY" "value" .Values.secrets.STORE_ENCRYPTION_KEY "length" 32) | quote }}
  NOVU_SECRET_KEY: {{ include "novu.generatedSecret" (dict "root" . "key" "NOVU_SECRET_KEY" "value" .Values.secrets.NOVU_SECRET_KEY "length" 64) | quote }}
  MONGODB_REPLICA_SET_KEY: {{ include "novu.generatedSecret" (dict "root" . "key" "MONGODB_REPLICA_SET_KEY" "value" .Values.secrets.MONGODB_REPLICA_SET_KEY "length" 756) | quote }}
  NEW_RELIC_LICENSE_KEY: {{ .Values.secrets.NEW_RELIC_LICENSE_KEY | quote }}
